spring.application.name=LMS

server.port=8080

spring.config.import=optional:file:.env
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# ===============================
# C?U HÌNH DATABASE MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/database_lms?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ===============================
# C?U HÌNH JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



jwt.secret=${JWT_SECRET}

# Th?i gian s?ng c?a Access Token: 15 phút
jwt.access-token.expiration=${JWT_ACCESS_EXPIRATION}
# Th?i gian s?ng c?a Refresh Token: 7 ngày
jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION}


spring.mail.host=smtp.gmail.com
spring.mail.port=587

# ??c t? bi?n MAIL_USERNAME, n?u không có thì m?c ??nh ?? tr?ng
spring.mail.username=${MAIL_USERNAME:}
# ??c t? bi?n MAIL_PASSWORD, n?u không có thì m?c ??nh ?? tr?ng
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true